#!/usr/bin/env python3

import sys
import os

def main():
    program = []
    options = ['./hd']
    pivot = 1

    for i, arg in enumerate(sys.argv[pivot:]):
        if arg in ("-h", "--help"):
            return os.system("./hd --help")
        elif arg in (
                '--32', '--64', '--chr', '--ord',
                '--table', '--extable', '-v', '--verbose'):
            options.append(arg)
            if i > pivot:
                pivot = i + 1
        else:
            program.append(arg)

    program = " ".join(program)
    options = " ".join(options)
    text = f"./hd.py {program} | xargs {options}"
    return os.system(text)

if __name__ == '__main__':
    exit(main())
